/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.xlido;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import com.crio.xlido.commands.AddQuestionCommand;
import com.crio.xlido.commands.CommandInvoker;
import com.crio.xlido.commands.CreateEventCommand;
import com.crio.xlido.commands.CreateUserCommand;
import com.crio.xlido.commands.DeleteEventCommand;
import com.crio.xlido.commands.DeleteQuestionCommand;
import com.crio.xlido.commands.ICommand;
import com.crio.xlido.commands.ListQuestionsCommand;
import com.crio.xlido.commands.ReplyQuestionCommand;
import com.crio.xlido.commands.UpVoteQuestionCommand;
import com.crio.xlido.respositories.EventRepository;
import com.crio.xlido.respositories.IEventRepository;
import com.crio.xlido.respositories.IQuestionRepository;
import com.crio.xlido.respositories.IReplyRepository;
import com.crio.xlido.respositories.IUserRepository;
import com.crio.xlido.respositories.QuestionRepository;
import com.crio.xlido.respositories.ReplyRepository;
import com.crio.xlido.respositories.UserRepository;
import com.crio.xlido.services.EventService;
import com.crio.xlido.services.QuestionService;
import com.crio.xlido.services.UserService;

public class App {
    // Repositories
    private final IUserRepository userRepository = new UserRepository();
    private final IEventRepository eventRepository = new EventRepository();
    private final IQuestionRepository questionRepository = new QuestionRepository();
    private final IReplyRepository replyRepository = new ReplyRepository();

    // Services
    private final UserService userService = new UserService(userRepository);
    private final EventService eventService = new EventService(userRepository, eventRepository, questionRepository);
    private final QuestionService questionService = new QuestionService(questionRepository, 
    replyRepository, userRepository, eventRepository);

    // Commands
    private final CommandInvoker commandInvoker = new CommandInvoker();
    private final ICommand createUserCommand = new CreateUserCommand(userService);
    private final ICommand createEventCommand = new CreateEventCommand(eventService);
    private final ICommand deleteEventCommand = new DeleteEventCommand(eventService);
    private final ICommand addQuestionCommand = new AddQuestionCommand(eventService);
    private final ICommand deleteQuestionCommand = new DeleteQuestionCommand(eventService);
    private final ICommand replyQuestionCommand = new ReplyQuestionCommand(questionService);
    private final ICommand upVoteQuestionCommand = new UpVoteQuestionCommand(questionService);
    private final ICommand listQuestionCommand =new ListQuestionsCommand(questionService);

    public static void main(String[] args) {

        // Test your code by ading commands in sample_input/sample_input_one.txt
        // Run run.sh script using "bash run.sh" in your terminal.
        if (args.length == 1){
            List<String> commandLineArgs = new LinkedList<>(Arrays.asList(args));
            String inputFile = commandLineArgs.get(0).split("=")[1];
            try {
                List<String> file_commands = Files.readAllLines(Paths.get(inputFile));
                // Execute the commands
                new App().run(file_commands);
            } catch (IOException e) {
                e.printStackTrace();
            }
            return;
        }        

        // OR
        // Test your code by adding commands in this list
        List<String> inplace_commands = new LinkedList<>(){
            {
                add("CREATE_USER,test1@user.com,abcd");
                add("CREATE_USER,test2@user.com,abcdefgh");
                add("CREATE_USER,test3@user.com,abcdefghi");
                add("CREATE_USER,test4@user.com,abcdefghij");
                add("CREATE_USER,test5@user.com,abcdefghijk");
                add("CREATE_EVENT,Event1,1");
                add("ADD_QUESTION,Is the mid-hinge resistant to outliers?,2,1");
                add("ADD_QUESTION,Is the mid-range resistant to outliers?,3,1");
                add("ADD_QUESTION,Is the mid-hinge a measure of centre or a measure of variability?,4,1");
                add("ADD_QUESTION,Is the mid-range a measure of centre or a measure of variability?,5,1");
                add("UPVOTE_QUESTION,1,1");
                add("UPVOTE_QUESTION,1,2");
                add("UPVOTE_QUESTION,1,3");
                add("UPVOTE_QUESTION,4,1");
                add("UPVOTE_QUESTION,4,5");
                add("REPLY_QUESTION,Yes. It is resistant to outliers,1,1");
                add("REPLY_QUESTION,Yes. It is resistant to outliers,2,1");
                add("LIST_QUESTIONS,1,POPULAR");
                add("LIST_QUESTIONS,2,POPULAR");
                add("LIST_QUESTIONS,1,RECENT");
                
            }
        };

        new App().run(inplace_commands);
 
    }
    public void registerCommands(){
        commandInvoker.registerCommand("CREATE_USER", createUserCommand);
        commandInvoker.registerCommand("CREATE_EVENT", createEventCommand);
        commandInvoker.registerCommand("DELETE_EVENT", deleteEventCommand);
        commandInvoker.registerCommand("ADD_QUESTION", addQuestionCommand);
        commandInvoker.registerCommand("DELETE_QUESTION", deleteQuestionCommand);
        commandInvoker.registerCommand("REPLY_QUESTION", replyQuestionCommand);
        commandInvoker.registerCommand("UPVOTE_QUESTION", upVoteQuestionCommand);
        commandInvoker.registerCommand("LIST_QUESTIONS", listQuestionCommand);
        

        
    }
    public void run(List<String> commands){

        Iterator<String> it = commands.iterator();
        while(it.hasNext()){
            String line = it.next();
                if(line == null){
                    break;
                }
                List<String> tokens = Arrays.asList(line.split(","));

                try {
                    //Execute Services
                    switch(tokens.get(0)){
                        case "CREATE_USER":
                        createUserCommand.invoke(tokens);
                        break;
                        case "CREATE_EVENT":
                        createEventCommand.invoke(tokens);
                        break;
                        case "DELETE_EVENT":
                        deleteEventCommand.invoke(tokens);
                        break;
                        case "ADD_QUESTION":
                        addQuestionCommand.invoke(tokens);
                        break;
                        case "DELETE_QUESTION":
                        deleteQuestionCommand.invoke(tokens);
                        break;
                        case "UPVOTE_QUESTION":
                        upVoteQuestionCommand.invoke(tokens);
                        break;
                        case "REPLY_QUESTION":
                        replyQuestionCommand.invoke(tokens);
                        break;
                        case "LIST_QUESTIONS":
                        listQuestionCommand.invoke(tokens);
                        break;
                        default:
                            throw new RuntimeException("INVALID_COMMAND");
                }
                } catch (Exception e) {
                    System.out.println("ERROR: " + e.getMessage());
                }
        }
    }
}
